In [1]:
import pandas
import numpy
from matplotlib import pyplot as plt
import seaborn
%matplotlib notebook
import datetime
import general
import discretionary_aua
import vantage_aua
import data_accessing
import combined
import revenue
import costs
import consolidated
import discf
pandas.set_option('display.float_format', '{:20,.4f}'.format)   #suppressing scientific notation
idx = pandas.IndexSlice

In [2]:
print('Pulling data...')
fund_dic = data_accessing.read_data(data_accessing.fund_data_name,data_accessing.fund_data_types)
nnb_dic = data_accessing.read_data(data_accessing.nnb_data_name,data_accessing.nnb_data_sheet)
discretionary_aua.append_share_class_units(fund_dic) # appending share class units
index_hl_dic = data_accessing.read_data(data_accessing.index_hl_data_name, data_accessing.index_hl_data_sheet)
data_dic = {**fund_dic, **index_hl_dic, **nnb_dic}

input_dic = data_accessing.read_data(data_accessing.assumptions_name, data_accessing.assumptions_sheet)
print('Data pulled successfully.')

Pulling data...
Data pulled successfully.

In [3]:
consolidated.revenue_analysis(data_dic, input_dic)

,,,,Platform fees,Net renewal income,Management fees,HL Fund AMC,Stockbroking income,Interest receivable,Adviser charges,Funds Library,Other income,Total revenue
month_end,financial_year,quarter_no,half_no,,,,,,,,,,
2017-06-30,2017,4,2,"88,800,000.0000","3,500,000.0000","14,500,000.0000","30,200,000.0000","33,500,000.0000","18,100,000.0000","5,850,000.0000","3,600,000.0000","5,150,000.0000","203,200,000.0000"
2017-12-29,2018,2,1,"101,841,948.4022","3,500,000.0000","16,078,212.3064","33,584,684.9283","34,157,000.0000","16,939,091.0608","5,850,000.0000","3,708,000.0000","5,124,880.0000","220,783,816.6977"
2018-06-29,2018,4,2,"110,138,718.3203","3,493,000.0000","16,532,574.6337","36,750,897.0035","34,827,010.0000","17,367,600.8571","5,850,000.0000","3,745,080.0000","5,245,084.0000","233,949,964.8146"
2018-12-31,2019,2,1,"117,349,787.7270","3,486,014.0000","16,981,618.1077","39,463,479.5989","35,510,288.9000","18,417,214.7269","5,850,000.0000","3,782,530.8000","5,371,298.2000","246,212,232.0605"
2019-06-28,2019,4,2,"125,579,629.7186","3,479,041.9720","17,405,800.9040","42,587,473.6964","36,207,100.7650","19,853,492.1240","5,850,000.0000","3,820,356.1080","5,503,823.1100","260,286,718.3980"
2019-12-31,2020,2,1,"106,297,129.5502","3,472,083.8881","17,825,389.5029","45,318,106.2820","36,917,714.9282","21,110,926.1668","5,850,000.0000","3,858,559.6691","5,642,974.2655","246,292,884.2527"
2020-06-30,2020,4,2,"113,036,588.2915","3,465,139.7203","18,267,031.2465","48,506,478.9532","37,642,406.0961","22,577,310.6074","5,850,000.0000","3,897,145.2658","5,789,082.9788","259,031,183.1595"
2020-12-31,2021,2,1,"119,117,641.2406","3,458,209.4408","18,705,931.2650","51,348,333.3482","38,381,454.4560","23,886,217.5044","5,850,000.0000","3,936,116.7184","5,942,497.1277","270,626,401.1013"
2021-06-30,2021,4,2,"126,261,467.5064","3,451,293.0220","19,169,780.7333","54,728,008.3797","39,135,145.7856","25,440,585.0114","5,850,000.0000","3,975,477.8856","6,103,581.9841","284,115,340.3081"
2021-12-31,2022,2,1,"132,707,383.6325","3,444,390.4359","19,630,660.8985","57,740,374.0385","39,903,771.5641","26,828,026.3223","5,850,000.0000","4,015,232.6645","6,272,721.0833","296,392,560.6395"
2022-06-30,2022,4,2,"140,279,839.4742","3,437,501.6550","20,117,923.4787","61,322,829.5718","40,687,629.0869","28,475,655.8797","5,850,000.0000","4,055,384.9911","6,450,317.1375","310,677,081.2749"
2022-12-30,2023,2,1,"147,112,510.5678","3,430,626.6517","20,601,973.6552","64,515,937.1701","41,487,021.5810","29,946,343.6692","5,850,000.0000","4,095,938.8410","6,636,792.9943","323,677,145.1304"
2023-06-30,2023,4,2,"155,139,313.7601","3,430,626.6517","21,113,923.2944","68,313,340.0354","42,302,258.3241","31,692,831.0001","5,850,000.0000","4,136,898.2294","6,832,592.6441","338,811,783.9394"
2023-12-29,2024,2,1,"162,381,945.1193","3,430,626.6517","21,622,400.9200","71,698,034.0896","43,133,654.7652","33,251,760.0570","5,850,000.0000","4,178,267.2117","7,038,182.2763","352,584,871.0909"
2024-06-28,2024,4,2,"170,890,356.5031","3,430,626.6517","22,160,384.1273","75,723,281.1269","43,981,532.6478","35,103,036.6277","5,850,000.0000","4,220,049.8838","7,254,051.3901","368,613,318.9585"
2024-12-31,2025,2,1,"178,567,545.7439","3,430,626.6517","22,694,618.1539","79,311,056.8244","44,846,220.1360","36,755,501.4280","5,850,000.0000","4,262,250.3827","7,480,713.9596","383,198,533.2802"
2025-06-30,2025,4,2,"187,586,461.8108","3,430,626.6517","23,260,058.2390","83,577,818.6838","45,728,051.9423","38,717,854.5930","5,850,000.0000","4,304,872.8865","7,718,709.6576","400,174,454.4647"
2025-12-31,2026,2,1,"195,724,282.4060","3,430,626.6517","23,821,453.3075","87,380,860.9231","46,627,369.4588","40,469,467.2813","5,850,000.0000","4,347,921.6154","7,968,605.1404","415,620,586.7843"
2026-06-30,2026,4,2,"205,284,333.4368","3,430,626.6517","24,415,854.8709","91,903,628.4942","47,544,520.8903","42,549,561.6362","5,850,000.0000","4,391,400.8315","8,230,995.3975","433,600,922.2092"
2026-12-31,2027,2,1,"213,910,423.2678","3,430,626.6517","25,005,895.7323","95,934,853.2679","48,479,861.3910","44,406,271.0858","5,850,000.0000","4,435,314.8398","8,506,505.1673","449,959,751.4036"
2027-06-30,2027,4,2,"224,044,077.3605","3,430,626.6517","25,630,849.4210","100,728,986.8932","49,433,753.2024","46,611,171.1020","5,850,000.0000","4,479,667.9882","8,795,790.4257","469,004,923.0447"
2027-12-31,2028,2,1,"233,187,732.5812","3,430,626.6517","26,251,105.6196","105,002,085.1533","50,406,565.7960","48,579,283.1185","5,850,000.0000","4,524,464.6681","9,099,539.9470","486,331,403.5355"
2028-06-30,2028,4,2,"243,929,405.9195","3,430,626.6517","26,908,293.1646","110,083,866.7961","51,398,676.0167","50,916,477.1357","5,850,000.0000","4,569,709.3148","9,418,476.9443","506,505,531.9434"
2028-12-29,2029,2,1,"253,621,680.4535","3,430,626.6517","27,560,423.9986","114,613,350.9518","52,410,468.2308","53,002,675.8733","5,850,000.0000","4,615,406.4080","9,753,360.7915","524,857,993.3593"
2029-06-29,2029,4,2,"265,007,854.1921","3,430,626.6517","28,251,623.5510","120,000,039.4932","53,442,334.4762","55,480,101.5314","5,850,000.0000","4,661,560.4720","10,104,988.8311","546,229,129.1988"
2029-12-31,2030,2,1,"275,281,665.1982","3,430,626.6517","28,937,383.3268","124,801,292.6982","54,494,674.6153","57,691,472.1933","5,850,000.0000","4,708,176.0768","10,474,198.2727","565,669,489.0329"
2030-06-28,2030,4,2,"287,351,009.3611","3,430,626.6517","29,664,475.1101","130,511,182.5521","55,567,896.4917","60,317,543.3909","5,850,000.0000","4,755,257.8375","10,861,868.1863","588,309,859.5814"
2030-12-31,2031,2,1,"298,241,249.0275","3,430,626.6517","30,385,718.7080","135,600,510.9495","56,662,416.0894","62,661,596.2925","5,850,000.0000","4,802,810.4159","11,268,921.5956","608,903,849.7301"
2031-06-30,2031,4,2,"311,034,753.8401","3,430,626.6517","31,150,691.0060","141,652,994.1946","57,778,657.6958","65,445,231.7620","5,850,000.0000","4,850,838.5201","11,696,327.6754","632,890,121.3456"
2031-12-31,2032,2,1,"322,578,407.8866","3,430,626.6517","31,909,379.7761","147,047,682.2957","58,917,054.0671","67,929,927.8376","5,850,000.0000","4,899,346.9053","12,145,104.0592","654,707,529.4793"
2032-06-30,2032,4,2,"336,139,522.9880","3,430,626.6517","32,714,335.2754","153,463,314.5356","60,078,046.5981","70,880,581.4353","5,850,000.0000","4,948,340.3743","12,616,319.2621","680,121,087.1205"
2032-12-31,2033,2,1,"345,170,636.9000","3,430,626.6517","33,461,347.6714","157,534,430.4233","61,262,085.4941","72,763,830.7474","5,850,000.0000","4,997,823.7781","13,111,095.2253","697,581,876.8913"
2033-06-30,2033,4,2,"350,863,113.5634","3,430,626.6517","34,169,828.7999","159,872,833.1420","62,469,629.9477","73,858,452.1648","5,850,000.0000","5,047,802.0158","13,630,609.9865","709,192,896.2719"

In [4]:
consolidated.costs_analysis(input_dic)

,,,,Staff costs,Marketing and distribution spend,"Depreciation, amortisation & financial costs",Office running costs,Other costs,FSCS levy costs,Total operating costs
month_end,financial_year,quarter_no,half_no,,,,,,,
2017-06-30,2017,4,2,"-36,700,000.0000","-8,500,000.0000","-5,700,000.0000","-2,400,000.0000","-14,500,000.0000","-4,500,000.0000","-72,300,000.0000"
2017-12-29,2018,2,1,"-37,606,490.0000","-8,755,000.0000","-5,871,000.0000","-2,459,280.0000","-14,858,150.0000","-2,250,000.0000","-71,799,920.0000"
2018-06-29,2018,4,2,"-38,535,370.3030","-8,971,248.5000","-6,016,013.7000","-2,520,024.2160","-15,225,146.3050","-2,362,500.0000","-73,630,303.0240"
2018-12-31,2019,2,1,"-39,487,193.9495","-9,192,838.3380","-6,164,609.2384","-2,582,268.8141","-15,601,207.4187","-2,480,625.0000","-75,508,742.7587"
2019-06-28,2019,4,2,"-40,462,527.6400","-9,419,901.4449","-6,316,875.0866","-2,646,050.8538","-15,986,557.2420","-2,604,656.2500","-77,436,568.5173"
2019-12-31,2020,2,1,"-41,461,952.0727","-9,652,573.0106","-6,472,901.9012","-2,711,408.3099","-16,381,425.2059","-2,734,889.0625","-79,415,149.5628"
2020-06-30,2020,4,2,"-42,486,062.2889","-9,890,991.5639","-6,632,782.5782","-2,778,380.0952","-16,786,046.4084","-2,871,633.5156","-81,445,896.4503"
2020-12-31,2021,2,1,"-43,535,468.0275","-10,135,299.0556","-6,796,612.3079","-2,847,006.0835","-17,200,661.7547","-3,015,215.1914","-83,530,262.4206"
2021-06-30,2021,4,2,"-44,610,794.0878","-10,385,640.9423","-6,964,488.6319","-2,917,327.1338","-17,625,518.1001","-3,165,975.9510","-85,669,744.8467"
2021-12-31,2022,2,1,"-45,712,680.7017","-10,642,166.2735","-7,136,511.5011","-2,989,385.1140","-18,060,868.3971","-3,324,274.7485","-87,865,886.7360"
2022-06-30,2022,4,2,"-46,841,783.9151","-10,905,027.7805","-7,312,783.3351","-3,063,222.9263","-18,506,971.8465","-3,490,488.4860","-90,120,278.2895"
2022-12-30,2023,2,1,"-47,998,775.9778","-11,174,381.9667","-7,493,409.0835","-3,138,884.5326","-18,964,094.0512","-3,665,012.9102","-92,434,558.5220"
2023-06-30,2023,4,2,"-49,184,345.7444","-11,450,389.2012","-7,678,496.2879","-3,216,414.9806","-19,432,507.1742","-3,848,263.5558","-94,810,416.9441"
2023-12-29,2024,2,1,"-50,399,199.0843","-11,733,213.8145","-7,868,155.1462","-3,295,860.4306","-19,912,490.1014","-4,040,676.7335","-97,249,595.3106"
2024-06-28,2024,4,2,"-51,644,059.3017","-12,023,024.1957","-8,062,498.5783","-3,377,268.1832","-20,404,328.6069","-4,242,710.5702","-99,753,889.4361"
2024-12-31,2025,2,1,"-52,919,667.5664","-12,319,992.8934","-8,261,642.2932","-3,460,686.7073","-20,908,315.5235","-4,454,846.0987","-102,325,151.0826"
2025-06-30,2025,4,2,"-54,226,783.3553","-12,624,296.7178","-8,465,704.8578","-3,546,165.6690","-21,424,750.9170","-4,677,588.4037","-104,965,289.9206"
2025-12-31,2026,2,1,"-55,566,184.9042","-12,936,116.8468","-8,674,807.7678","-3,633,755.9610","-21,953,942.2646","-4,911,467.8239","-107,676,275.5683"
2026-06-30,2026,4,2,"-56,938,669.6713","-13,255,638.9329","-8,889,075.5197","-3,723,509.7333","-22,496,204.6385","-5,157,041.2151","-110,460,139.7108"
2026-12-31,2027,2,1,"-58,345,054.8122","-13,583,053.2145","-9,108,635.6850","-3,815,480.4237","-23,051,860.8931","-5,414,893.2758","-113,318,978.3043"
2027-06-30,2027,4,2,"-59,786,177.6661","-13,918,554.6289","-9,333,618.9864","-3,909,722.7902","-23,621,241.8572","-5,685,637.9396","-116,254,953.8683"
2027-12-31,2028,2,1,"-61,262,896.2544","-14,262,342.9282","-9,564,159.3754","-4,006,292.9431","-24,204,686.5310","-5,969,919.8366","-119,270,297.8688"
2028-06-30,2028,4,2,"-62,776,089.7919","-14,614,622.7986","-9,800,394.1120","-4,105,248.3788","-24,802,542.2884","-6,268,415.8284","-122,367,313.1980"
2028-12-29,2029,2,1,"-64,326,659.2098","-14,975,603.9817","-10,042,463.8465","-4,206,648.0137","-25,415,165.0829","-6,581,836.6198","-125,548,376.7544"
2029-06-29,2029,4,2,"-65,915,527.6923","-15,345,501.4000","-10,290,512.7036","-4,310,552.2197","-26,042,919.6604","-6,910,928.4508","-128,815,942.1268"
2029-12-31,2030,2,1,"-67,543,641.2263","-15,724,535.2846","-10,544,688.3673","-4,417,022.8595","-26,686,179.7760","-7,256,474.8734","-132,172,542.3871"
2030-06-28,2030,4,2,"-69,211,969.1645","-16,112,931.3062","-10,805,142.1700","-4,526,123.3241","-27,345,328.4165","-7,619,298.6170","-135,620,792.9983"
2030-12-31,2031,2,1,"-70,921,504.8029","-16,510,920.7094","-11,072,029.1816","-4,637,918.5702","-28,020,758.0284","-8,000,263.5479","-139,163,394.8404"
2031-06-30,2031,4,2,"-72,673,265.9715","-16,918,740.4509","-11,345,508.3024","-4,752,475.1589","-28,712,870.7517","-8,400,276.7253","-142,803,137.3607"
2031-12-31,2032,2,1,"-74,468,295.6410","-17,336,633.3401","-11,625,742.3575","-4,869,861.2953","-29,422,078.6593","-8,820,290.5615","-146,542,901.8547"
2032-06-30,2032,4,2,"-76,307,662.5434","-17,764,848.1836","-11,912,898.1937","-4,990,146.8693","-30,148,804.0021","-9,261,305.0896","-150,385,664.8817"
2032-12-31,2033,2,1,"-78,192,461.8082","-18,203,639.9337","-12,207,146.7791","-5,113,403.4970","-30,893,479.4610","-9,724,370.3441","-154,334,501.8231"
2033-06-30,2033,4,2,"-80,123,815.6149","-18,653,269.8401","-12,508,663.3045","-5,239,704.5634","-31,656,548.4037","-10,210,588.8613","-158,392,590.5878"

In [5]:
consolidated.annual_revenue_analysis(data_dic, input_dic)

,Platform fees,Net renewal income,Management fees,HL Fund AMC,Stockbroking income,Interest receivable,Adviser charges,Funds Library,Other income,Total revenue
financial_year,,,,,,,,,,
2018,"211,980,666.7225","6,993,000.0000","32,610,786.9401","70,335,581.9318","68,984,010.0000","34,306,691.9179","11,700,000.0000","7,453,080.0000","10,369,964.0000","454,733,781.5123"
2019,"242,929,417.4455","6,965,055.9720","34,387,419.0118","82,050,953.2952","71,717,389.6650","38,270,706.8509","11,700,000.0000","7,602,886.9080","10,875,121.3100","506,498,950.4585"
2020,"219,333,717.8417","6,937,223.6083","36,092,420.7494","93,824,585.2352","74,560,121.0243","43,688,236.7742","11,700,000.0000","7,755,704.9349","11,432,057.2443","505,324,067.4122"
2021,"245,379,108.7470","6,909,502.4628","37,875,711.9983","106,076,341.7279","77,516,600.2416","49,326,802.5159","11,700,000.0000","7,911,594.6040","12,046,079.1118","554,741,741.4094"
2022,"272,987,223.1067","6,881,892.0910","39,748,584.3771","119,063,203.6103","80,591,400.6510","55,303,682.2020","11,700,000.0000","8,070,617.6556","12,723,038.2208","607,069,641.9144"
2023,"302,251,824.3280","6,861,253.3035","41,715,896.9496","132,829,277.2055","83,789,279.9051","61,639,174.6694","11,700,000.0000","8,232,837.0705","13,469,385.6384","662,488,929.0699"
2024,"333,272,301.6225","6,861,253.3035","43,782,785.0473","147,421,315.2165","87,115,187.4130","68,354,796.6847","11,700,000.0000","8,398,317.0956","14,292,233.6663","721,198,190.0494"
2025,"366,154,007.5547","6,861,253.3035","45,954,676.3929","162,888,875.5082","90,574,272.0783","75,473,356.0210","11,700,000.0000","8,567,123.2692","15,199,423.6171","783,372,987.7449"
2026,"401,008,615.8428","6,861,253.3035","48,237,308.1785","179,284,489.4173","94,171,890.3491","83,019,028.9175","11,700,000.0000","8,739,322.4469","16,199,600.5379","849,221,508.9935"
2027,"437,954,500.6282","6,861,253.3035","50,636,745.1534","196,663,840.1610","97,913,614.5934","91,017,442.1878","11,700,000.0000","8,914,982.8281","17,302,295.5930","918,964,674.4484"
2028,"477,117,138.5008","6,861,253.3035","53,159,398.7843","215,085,951.9494","101,805,241.8126","99,495,760.2542","11,700,000.0000","9,094,173.9829","18,518,016.8913","992,836,935.4789"
2029,"518,629,534.6457","6,861,253.3035","55,812,047.5496","234,613,390.4450","105,852,802.7070","108,482,777.4047","11,700,000.0000","9,276,966.8800","19,858,349.6227","1,071,087,122.5581"
2030,"562,632,674.5592","6,861,253.3035","58,601,858.4369","255,312,475.2503","110,062,571.1069","118,009,015.5842","11,700,000.0000","9,463,433.9143","21,336,066.4590","1,153,979,348.6143"
2031,"609,276,002.8676","6,861,253.3035","61,536,409.7140","277,253,505.1440","114,441,073.7852","128,106,828.0544","11,700,000.0000","9,653,648.9360","22,965,249.2710","1,241,793,971.0758"
2032,"658,717,930.8745","6,861,253.3035","64,623,715.0515","300,510,996.8313","118,995,100.6652","138,810,509.2729","11,700,000.0000","9,847,687.2796","24,761,423.3213","1,334,828,616.5998"
2033,"696,033,750.4634","6,861,253.3035","67,631,176.4713","317,407,263.5653","123,731,715.4419","146,622,282.9122","11,700,000.0000","10,045,625.7939","26,741,705.2118","1,406,774,773.1632"

In [6]:
consolidated.annual_costs_analysis(input_dic)

,Staff costs,Marketing and distribution spend,"Depreciation, amortisation & financial costs",Office running costs,Other costs,FSCS levy costs,Total operating costs
financial_year,,,,,,,
2018,"-76,141,860.3030","-17,726,248.5000","-11,887,013.7000","-4,979,304.2160","-30,083,296.3050","-4,612,500.0000","-145,430,223.0240"
2019,"-79,949,721.5895","-18,612,739.7828","-12,481,484.3250","-5,228,319.6680","-31,587,764.6607","-5,085,281.2500","-152,945,311.2760"
2020,"-83,948,014.3617","-19,543,564.5745","-13,105,684.4794","-5,489,788.4051","-33,167,471.6143","-5,606,522.5781","-160,861,046.0132"
2021,"-88,146,262.1152","-20,520,939.9978","-13,761,100.9397","-5,764,333.2173","-34,826,179.8548","-6,181,191.1424","-169,200,007.2673"
2022,"-92,554,464.6168","-21,547,194.0540","-14,449,294.8362","-6,052,608.0403","-36,567,840.2437","-6,814,763.2345","-177,986,165.0255"
2023,"-97,183,121.7222","-22,624,771.1679","-15,171,905.3714","-6,355,299.5132","-38,396,601.2254","-7,513,276.4660","-187,244,975.4660"
2024,"-102,043,258.3860","-23,756,238.0102","-15,930,653.7245","-6,673,128.6138","-40,316,818.7084","-8,283,387.3038","-197,003,484.7466"
2025,"-107,146,450.9218","-24,944,289.6112","-16,727,347.1510","-7,006,852.3764","-42,333,066.4405","-9,132,434.5024","-207,290,441.0032"
2026,"-112,504,854.5755","-26,191,755.7796","-17,563,883.2875","-7,357,265.6943","-44,450,146.9031","-10,068,509.0389","-218,136,415.2790"
2027,"-118,131,232.4783","-27,501,607.8434","-18,442,254.6715","-7,725,203.2138","-46,673,102.7503","-11,100,531.2154","-229,573,932.1727"
2028,"-124,038,986.0463","-28,876,965.7268","-19,364,553.4874","-8,111,541.3218","-49,007,228.8194","-12,238,335.6650","-241,637,611.0668"
2029,"-130,242,186.9020","-30,321,105.3817","-20,332,976.5501","-8,517,200.2334","-51,458,084.7433","-13,492,765.0706","-254,364,318.8812"
2030,"-136,755,610.3908","-31,837,466.5908","-21,349,830.5373","-8,943,146.1836","-54,031,508.1925","-14,875,773.4904","-267,793,335.3854"
2031,"-143,594,770.7744","-33,429,661.1604","-22,417,537.4840","-9,390,393.7291","-56,733,628.7801","-16,400,540.2731","-281,966,532.2012"
2032,"-150,775,958.1844","-35,101,481.5237","-23,538,640.5512","-9,860,008.1646","-59,570,882.6614","-18,081,595.6511","-296,928,566.7364"
2033,"-158,316,277.4230","-36,856,909.7738","-24,715,810.0836","-10,353,108.0604","-62,550,027.8647","-19,934,959.2054","-312,727,092.4109"

In [7]:
consolidated.get_nnb_compare(data_dic, input_dic,[2017,2018,2019])

                                Vantage nnb              PMS nnb  \
financial_year half_no
2017           1         2,316,600,000.0000      23,400,000.0000
               2         4,514,400,000.0000      45,600,000.0000
2018           1         2,715,005,465.1139      20,171,425.2810
               2         5,320,610,426.6667      39,530,047.7476
2019           1         2,777,297,646.7938      20,634,231.7485
               2         5,075,862,347.0400      37,711,665.5512

                             HLMM Funds nnb            Total nnb
financial_year half_no
2017           1           374,400,000.0000   2,340,000,000.0000
               2           729,600,000.0000   4,560,000,000.0000
2018           1           355,632,484.3615   2,735,176,890.3950
               2           696,934,841.8147   5,360,140,474.4143
2019           1           363,791,997.7075   2,797,931,878.5423
               2           664,875,839.0912   5,113,574,012.5912

In [8]:
consolidated.get_aua_compare(data_dic, input_dic,[2017,2018,2019])

                                     Actual                       \
                                Vantage AUA              PMS AUA
financial_year half_no
2017           1        66,792,000,000.0000   3,209,000,000.0000
               2        75,700,000,000.0000   3,500,000,000.0000
2018           1                        nan                  nan
               2                        nan                  nan
2019           1                        nan                  nan
               2                        nan                  nan

                                                                  \
                             HLMM Funds AUA            Total AUA
financial_year half_no
2017           1         7,581,000,000.0000  70,001,000,000.0000
               2         8,900,000,000.0000  79,200,000,000.0000
2018           1                        nan                  nan
               2                        nan                  nan
2019           1                        nan                  nan
               2                        nan                  nan

                                WP forecast                       \
                                Vantage AUA              PMS AUA
financial_year half_no
2017           1                        nan                  nan
               2        75,700,000,000.0000   3,500,000,000.0000
2018           1        81,303,255,597.8987   3,604,643,036.6999
               2        88,955,541,550.0829   3,750,203,054.8909
2019           1        94,133,446,078.8287   3,880,001,822.5939
               2       101,680,884,482.9173   4,030,105,256.8151


                             HLMM Funds AUA            Total AUA
financial_year half_no
2017           1                        nan                  nan
               2         8,900,000,000.0000  79,200,000,000.0000
2018           1         9,471,197,224.4295  84,907,898,634.5986
               2        10,438,711,999.9535  92,705,744,604.9738
2019           1        11,081,083,089.7655  98,013,447,901.4226
               2        12,032,773,658.5886 105,710,989,739.7323

In [9]:
consolidated.get_revenue_compare(data_dic, input_dic,False,[2017,2018,2019])

                                  Actual                       \
financial_year                      2017                 2018
Platform fees           169,300,000.0000                  nan
Net renewal income        6,300,000.0000                  nan
Management fees          28,200,000.0000                  nan
HL Fund AMC              56,500,000.0000                  nan
Stockbroking income      61,600,000.0000                  nan
Interest receivable      36,600,000.0000                  nan
Adviser charges          11,000,000.0000                  nan
Funds Library             7,500,000.0000                  nan
Other income              8,800,000.0000                  nan
Total revenue           385,800,000.0000               0.0000

                                                  WP forecast  \
financial_year                      2019                 2017
Platform fees                        nan                  nan
Net renewal income                   nan                  nan
Management fees                      nan                  nan
HL Fund AMC                          nan                  nan
Stockbroking income                  nan                  nan
Interest receivable                  nan                  nan
Adviser charges                      nan                  nan
Funds Library                        nan                  nan
Other income                         nan                  nan
Total revenue                     0.0000                  nan


financial_year                      2018                 2019
Platform fees           211,980,666.7225     242,929,417.4455
Net renewal income        6,993,000.0000       6,965,055.9720
Management fees          32,610,786.9401      34,387,419.0118
HL Fund AMC              70,335,581.9318      82,050,953.2952
Stockbroking income      68,984,010.0000      71,717,389.6650
Interest receivable      34,306,691.9179      38,270,706.8509
Adviser charges          11,700,000.0000      11,700,000.0000
Funds Library             7,453,080.0000       7,602,886.9080
Other income             10,369,964.0000      10,875,121.3100
Total revenue           454,733,781.5123     506,498,950.4585

In [10]:
consolidated.get_costs_compare(input_dic,False,[2017,2018,2019])

                                                           Actual  \
financial_year                                               2017
Staff costs                                       68,600,000.0000
Marketing and distribution spend                  14,300,000.0000
Depreciation, amortisation & financial costs       9,000,000.0000
Office running costs                               4,200,000.0000
Other costs                                       26,400,000.0000
FSCS levy costs                                    4,200,000.0000
Total operating costs                            126,700,000.0000

                                                                   \
financial_year                                               2018
Staff costs                                                   nan
Marketing and distribution spend                              nan
Depreciation, amortisation & financial costs                  nan
Office running costs                                          nan
Other costs                                                   nan
FSCS levy costs                                               nan
Total operating costs                                      0.0000

                                                                   \
financial_year                                               2019
Staff costs                                                   nan
Marketing and distribution spend                              nan
Depreciation, amortisation & financial costs                  nan
Office running costs                                          nan
Other costs                                                   nan
FSCS levy costs                                               nan
Total operating costs                                      0.0000

                                                      WP forecast  \
financial_year                                               2017
Staff costs                                                   nan
Marketing and distribution spend                              nan
Depreciation, amortisation & financial costs                  nan
Office running costs                                          nan
Other costs                                                   nan
FSCS levy costs                                               nan
Total operating costs                                         nan

                                                                   \
financial_year                                               2018
Staff costs                                       76,141,860.3030
Marketing and distribution spend                  17,726,248.5000
Depreciation, amortisation & financial costs      11,887,013.7000
Office running costs                               4,979,304.2160
Other costs                                       30,083,296.3050
FSCS levy costs                                    4,612,500.0000
Total operating costs                            145,430,223.0240


financial_year                                               2019
Staff costs                                       79,949,721.5895
Marketing and distribution spend                  18,612,739.7828
Depreciation, amortisation & financial costs      12,481,484.3250
Office running costs                               5,228,319.6680
Other costs                                       31,587,764.6607
FSCS levy costs                                    5,085,281.2500
Total operating costs                            152,945,311.2760

In [11]:
discf.disc_cash_flow(data_dic, input_dic)

financial_year,2018,2019,2020,2021,2022,2023,2024,2025,2026
EBIT,"310,452,960.0339","354,743,387.8946","345,694,533.5747","386,816,475.7942","430,402,965.4912","476,609,759.8979","525,608,455.1673","577,545,923.1285","632,599,838.6513"
Tax,"58,986,062.4064","67,401,243.7000","65,681,961.3792","73,495,130.4009","81,776,563.4433","90,555,854.3806","99,865,606.4818","109,733,725.3944","120,193,969.3438"
EAT,"251,466,897.6275","287,342,144.1946","280,012,572.1955","313,321,345.3933","348,626,402.0479","386,053,905.5173","425,742,848.6855","467,812,197.7341","512,405,869.3076"
Depreciation,"11,887,013.7000","12,481,484.3250","13,105,684.4794","13,761,100.9397","14,449,294.8362","15,171,905.3714","15,930,653.7245","16,727,347.1510","17,563,883.2875"
Capital Expenditure,"16,805,151.7290","17,645,578.8794","18,528,035.8673","19,454,624.6085","20,427,552.1361","21,449,135.8569","22,521,809.0716","23,648,126.7702","24,830,771.7183"
Free cash flow,"246,548,759.5985","282,178,049.6402","274,590,220.8076","307,627,821.7244","342,648,144.7480","379,776,675.0317","419,151,693.3385","460,891,418.1149","505,138,980.8768"
Discounted cash flow,"227,758,669.3750","240,806,062.9820","216,471,811.3863","224,034,029.4943","230,520,131.9850","236,026,549.6716","240,644,472.0922","244,441,748.3703","247,491,186.9318"

In [12]:
discf.fair_value(data_dic, input_dic)

                                       HL
Terminal value        11,646,259,836.8817
Enterprise value       7,814,241,472.1063
Net debt&cash            211,000,000.0000
Fair value             8,025,241,472.1063
No. of shares                   474720010
Fair value per share              16.9052

In [13]:

consolidated.aua_analysis(data_dic, input_dic)

                                           Vantage AUA              PMS AUA  \
financial_year quarter_no half_no
2017           4          2        75,700,000,000.0000   3,500,000,000.0000
2018           2          1        81,303,255,597.8987   3,604,643,036.6999
               4          2        88,955,541,550.0829   3,750,203,054.8909
2019           2          1        94,133,446,078.8287   3,880,001,822.5939
               4          2       101,680,884,482.9173   4,030,105,256.8151
2020           2          1       107,005,911,310.8544   4,166,476,823.5994
               4          2       114,707,284,125.4182   4,323,365,665.7914
2021           2          1       120,351,812,563.0316   4,467,919,526.5829
               4          2       128,515,267,746.4692   4,634,221,699.3064
2022           2          1       134,498,467,890.3394   4,787,448,791.7453
               4          2       143,151,730,384.7833   4,963,729,094.8323
2023           2          1       149,493,922,537.2857   5,126,149,812.8175
               4          2       158,666,380,781.3961   5,313,006,934.0897
2024           2          1       165,389,104,463.0487   5,485,172,895.1540
               4          2       175,111,910,201.8058   5,683,241,443.7025
2025           2          1       182,237,997,304.3575   5,865,737,362.4307
               4          2       192,544,171,387.4401   6,075,690,023.8921
2026           2          1       200,097,823,716.1449   6,269,135,697.7441
               4          2       211,022,368,244.2124   6,491,685,518.8931
2027           2          1       219,029,239,712.6396   6,696,737,933.1762
               4          2       230,609,256,912.3911   6,932,640,743.5942
2028           2          1       239,096,540,668.9238   7,149,996,302.7342
               4          2       251,371,358,900.6605   7,400,053,281.7773
2029           2          1       260,367,879,682.5851   7,630,450,174.4658
               4          2       273,379,187,008.2259   7,895,510,572.2515
2030           2          1       282,915,499,037.0662   8,139,731,278.5012
               4          2       296,707,484,802.2455   8,420,695,300.1540
2031           2          1       306,815,975,552.8160   8,679,569,248.7787
               4          2       321,435,480,463.9061   8,977,391,111.7307
2032           2          1       332,150,480,659.5109   9,251,797,497.2729
               4          2       347,647,155,865.2663   9,567,488,672.0021
2033           2          1       353,074,697,460.8830   9,814,299,203.1696
               4          2       358,662,693,545.2119  10,068,406,197.5498

                                        HLMM Funds AUA            Total AUA
financial_year quarter_no half_no
2017           4          2         8,900,000,000.0000  79,200,000,000.0000
2018           2          1         9,471,197,224.4295  84,907,898,634.5986
               4          2        10,438,711,999.9535  92,705,744,604.9738
2019           2          1        11,081,083,089.7655  98,013,447,901.4226
               4          2        12,032,773,658.5886 105,710,989,739.7323
2020           2          1        12,692,263,707.2575 111,172,388,134.4539
               4          2        13,661,901,910.7969 119,030,649,791.2096
2021           2          1        14,360,961,362.3860 124,819,732,089.6145
               4          2        15,388,777,858.1377 133,149,489,445.7756
2022           2          1        16,129,780,876.8221 139,285,916,682.0847
               4          2        17,219,266,362.3189 148,115,459,479.6155
2023           2          1        18,004,729,562.1245 154,620,072,350.1032
               4          2        19,159,584,176.7511 163,979,387,715.4858
2024           2          1        19,992,175,168.5449 170,874,277,358.2027
               4          2        21,216,321,060.0491 180,795,151,645.5083
2025           2          1        22,098,867,511.3506 188,103,734,666.7883
               4          2        23,396,462,156.3451 198,619,861,411.3322
2026           2          1        24,331,961,394.7247 206,366,959,413.8890
               4          2        25,707,411,718.4188 217,514,053,763.1056
2027           2          1        26,699,040,911.1012 225,725,977,645.8157
               4          2        28,157,018,254.2169 237,541,897,655.9853
2028           2          1        29,208,145,198.4602 246,246,536,971.6581
               4          2        30,753,601,182.1629 258,771,412,182.4378
2029           2          1        31,867,795,743.0608 267,998,329,857.0509
               4          2        33,505,979,085.7857 281,274,697,580.4774
2030           2          1        34,687,025,320.3375 291,055,230,315.5673
               4          2        36,423,499,663.6259 305,128,180,102.3995
2031           2          1        37,675,408,672.2507 315,495,544,801.5948
               4          2        39,516,071,476.1364 330,412,871,575.6368
2032           2          1        40,843,095,025.2788 341,402,278,156.7838
               4          2        42,794,197,597.3976 357,214,644,537.2684
2033           2          1        43,424,038,168.7269 362,888,996,664.0526
               4          2        44,072,498,725.7464 368,731,099,742.7617